<?xml version="1.0" standalone="yes"?>
<?xml-stylesheet href="sample.css"?>
<!-- Description: To test the entity declaration in the DTD -->
<!-- Author:  Chris Petersen Date: 10/25/2000 -->
<!-- 
   - The contents of this file are subject to the Mozilla Public
   - License Version 1.1 (the "License"); you may not use this file
   - except in compliance with the License. You may obtain a copy of
   - the License at http://www.mozilla.org/MPL/
   - 
   - Software distributed under the License is distributed on an "AS
   - IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
   - implied. See the License for the specific language governing
   - rights and limitations under the License.
   - 
   - The Original Code is Mozilla Communicator Test Cases.
   - 
   - The Initial Developer of the Original Code is Netscape Communications
   - Corp.  Portions created by Netscape Communications Corp. are 
   - Copyright (C) 2000 Netscape Communications Corp.  All
   - Rights Reserved.
   - 
   - Contributor(s): 
  -->
<!-- Purpose: To test the entity declaration in the DTD -->
<!-- Expected result: The entity "replacement text " should appear in the document -->

<!DOCTYPE main [
<!ELEMENT text (#PCDATA) >
<!ENTITY poem1 "Humpty Dumpty sat on a wall ">
<!ENTITY poem2 "Humpty Dumpty had a great fall">
<!ENTITY poem3 " All the King's horses and All the Kings's men">
<!ENTITY poem4 "Couldn't put him back together again">
]>
<main>
<text>There should be a rhyme below:</text>
<text>&poem1;</text>
<text>&poem2;</text>
<text>&poem3;</text>
<text>&poem4;</text>
</main>

