<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="idkey57.xsl"?>
<!DOCTYPE main [
  <!ELEMENT main (a*)>
  <!ATTLIST main list CDATA #REQUIRED>
  <!ELEMENT a (#PCDATA)>
  <!ATTLIST a id ID #REQUIRED>
]>
<main list="y w z">
  <a id="w">W</a>
  <a id="x">X</a>
  <a id="y">Y</a>
  <a id="z">Z</a>
</main>
